name: Pipeline CI/CD
run-name: Pipeline Ci/CD executada por ${{ github.actor }} em ${{ github.run_number }}
on: 
    workflow_dispatch:
    push: 
      branches:
        - main
jobs:
    build:
      name: Buikd
      runs-on: ubuntu-latest
      steps:
          - name: obtendo cod projeto
            uses: actions/checkout@v4
          - name: Setuo dotnet
            uses: actions/setup-dotnet@v4
            with:
              dotnet-vevrsion: "8.0.300"
          - name: Execução do comando build
            working-directory: ./src
            run: dotnet build Review-Filmes.sln
    testes:
      needs: [build]
      uses: joao-pedro-rdo/desafio-cicd-01/.github/workflows/testes.yml@main